[package]
name = "jazz"
version = "0.1.0"
authors = ["playx"]
edition = "2018"

[dependencies]
hmap = "0.1"
fxhash = "0.2"
rand = "0.6"
walkdir = "2.2"
hashbrown = "0.1"
gc = "0.3"
time = "0.1"
structopt = "0.2"
crossterm = "0.6"

waffle = {git = "https://github.com/jazz-lang/waffle"}
