[package]
name = "jazz"
version = "0.1.0"
authors = ["playXE <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.7.1"
wrc = "0.4"
lazy_static = "1.3"
colored = "1.8"
pretty_backtrace = "0.1"
llvm-sys = "80"